class TestRunStorage {
  static demoApiTests1 = [
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '1',
      to_investigate: '',
    },
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
    {
      total: '8',
      passed: '1',
      failed: '7',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '7',
      to_investigate: '4',
    },
  ];

  static demoApiTests2 = [
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '1',
      to_investigate: '',
    },
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
    {
      total: '8',
      passed: '5',
      failed: '3',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '3',
      to_investigate: '3',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
    {
      total: '5',
      passed: '',
      failed: '4',
      skipped: '1',
      product_bug: '1',
      automation_bug: '4',
      system_issue: '',
      to_investigate: '3',
    },
  ];

  static demoApiTests3 = [
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '8',
      passed: '8',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
    {
      total: '5',
      passed: '2',
      failed: '1',
      skipped: '2',
      product_bug: '',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '5',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
    {
      total: '5',
      passed: '',
      failed: '5',
      skipped: '',
      product_bug: '4',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '3',
    },
  ];

  static demoApiTests4 = [
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '1',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '1',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '8',
      passed: '8',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '5',
      passed: '5',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '5',
      passed: '5',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
    {
      total: '5',
      passed: '2',
      failed: '3',
      skipped: '',
      product_bug: '3',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
  ];

  static demoApiTests5 = [
    {
      total: '1',
      passed: '1',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '1',
      passed: '1',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '8',
      passed: '8',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '5',
      passed: '5',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '5',
      passed: '5',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '5',
      passed: '5',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '5',
      passed: '5',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
  ];

  static demoApiTests6 = [
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '1',
      to_investigate: '',
    },
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
    {
      total: '8',
      passed: '1',
      failed: '7',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '7',
      to_investigate: '4',
    },
  ];

  static demoApiTests7 = [
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '1',
      to_investigate: '',
    },
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
    {
      total: '8',
      passed: '5',
      failed: '3',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '3',
      to_investigate: '3',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
    {
      total: '5',
      passed: '',
      failed: '4',
      skipped: '1',
      product_bug: '1',
      automation_bug: '4',
      system_issue: '',
      to_investigate: '3',
    },
  ];

  static demoApiTests8 = [
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '8',
      passed: '8',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
    {
      total: '5',
      passed: '2',
      failed: '1',
      skipped: '2',
      product_bug: '',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '5',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
    {
      total: '5',
      passed: '',
      failed: '5',
      skipped: '',
      product_bug: '4',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '3',
    },
  ];

  static demoApiTests9 = [
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '1',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '1',
      passed: '',
      failed: '1',
      skipped: '',
      product_bug: '',
      automation_bug: '1',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '8',
      passed: '8',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '5',
      passed: '5',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '5',
      passed: '5',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
    {
      total: '5',
      passed: '2',
      failed: '3',
      skipped: '',
      product_bug: '3',
      automation_bug: '',
      system_issue: '',
      to_investigate: '1',
    },
  ];

  static demoApiTests10 = [
    {
      total: '1',
      passed: '1',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '1',
      passed: '1',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '8',
      passed: '8',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '5',
      passed: '5',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '5',
      passed: '5',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '5',
      passed: '5',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '',
      passed: '',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
    {
      total: '5',
      passed: '5',
      failed: '',
      skipped: '',
      product_bug: '',
      automation_bug: '',
      system_issue: '',
      to_investigate: '',
    },
  ];
}

module.exports = { TestRunStorage };
